Algoritmo "Váriaveis 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Conhecendo variáveis
// Autor(a)    : Lucas Alves
// Data atual  : 06/12/2021
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          cidade, endereco, primeiroNome, segundoNome: caractere
          idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo